= liferay-reference
Pawel Kruszewski <kruszewsky@gmail.com>
v7.3.5, 2020-11-28
:toc:


== About
The project serves as an index of Liferay CE 7 code. It’s meant to
include all Liferay 7 code as dependency.

== Problem it solves

[quote, All Liferay Developers I Know]
____
Where should I look for such API? How is that API used in Liferay itself?
____

Liferay is a huge project. It consist of hundreds of modules distributed as jar/war files. Each with it's own sources.
Once in a while you need to check one or two source files or have a peek into default configuration.
The project delivers handy index of all Liferay sources.

== Basic facts

* The project uses `release.portal.bom`,`release.portal.bom.compile.only` and `release.portal.bom.third.party` artifacts from Liferay to retrieve _almost all_
  footnote:[Some of the dependencies are not provided in `release.portal.bom`,`release.portal.bom.compile.only` and `release.portal.bom.third.party`
            or provided with a wrong type e.g. default `jar` when it's a `war` dependency. Those dependencies are curated in `pom.xml` section named
            "fix for broken bom dependencies"]
  dependency versions.
* The project is not meant to be built.
* The project contains no own sources.

== Usage

It’s meant to be opened with an IDE that supports maven an can index all
dependencies together with sources like Intellij IDEA for example.

Once imported user can leverage all IDE tools like Intellij IDEA
https://www.jetbrains.com/help/idea/structural-search-and-replace.html[structural
search],
https://www.jetbrains.com/help/idea/navigating-through-the-source-code.html#go_to_implementation[go
to implementation], full text search etc. to find API’s and sources he’s
interested in.

== Alternative solution

The project creates IntelliJ IDEA project modules that contains whole
Liferay 7 code: https://github.com/holatuwol/liferay-intellij

== Supported Liferay Portal versions

. Liferay CE 7.3.5: link:https://github.com/ktor/liferay-reference/blob/7.3.5/pom.xml[dependency listing] |
https://github.com/synus-org/liferay-reference/tree/7.3.5[tag]
. Liferay CE 7.2.1: link:https://github.com/ktor/liferay-reference/blob/7.2.1/dependency-listing-7.2.1.txt[dependency listing] |
https://github.com/synus-org/liferay-reference/tree/7.2.1[tag]
. Liferay CE 7.2.0: link:https://github.com/ktor/liferay-reference/blob/7.2.0/dependency-listing-7.2.0.txt[dependency listing] |
https://github.com/synus-org/liferay-reference/tree/7.2.0[tag]
. Liferay CE 7.1.2: link:https://github.com/synus-org/liferay-reference/blob/7.1.2.2/dependency-listing-7.1.2.txt[dependency listing] |
https://github.com/synus-org/liferay-reference/tree/7.1.2.2[tag]

== License

LGPL-2.1
